# Generated by Django 5.0 on 2023-12-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_chainstatus_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chainstatus',
            old_name='chain1',
            new_name='status',
        ),
    ]
