# Generated by Django 5.0 on 2023-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_chain1_chainstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField(null='true')),
                ('two', models.IntegerField(null='true')),
                ('three', models.IntegerField(null='true')),
                ('four', models.IntegerField(null='true')),
            ],
        ),
    ]
