# Generated by Django 4.2.7 on 2023-12-15 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('request_data', models.TextField(verbose_name='Тело запроса')),
                ('response_data', models.TextField(blank=True, null=True, verbose_name='Тело ответа')),
            ],
        ),
    ]
